<?php

namespace App\Enums;

enum DegreeEnum: string
{
    case BSIT = 'BACHELOR OF SCIENCE IN INFORMATION TECHNOLOGY';
    case BSCS = 'BACHELOR OF SCIENCE IN COMPUTER SCIENCE';
    case BSGD = 'BACHELOR OF SCIENCE IN GAME DEVELOPMENT';
    case BSIS = 'BACHELOR OF SCIENCE IN INFORMATION SYSTEMS';
    case BSECE = 'BACHELOR OF SCIENCE IN ELECTRONICS ENGINEERING';
    case BSCPE = 'BACHELOR OF SCIENCE IN COMPUTER ENGINEERING';
    case BSME = 'BACHELOR OF SCIENCE IN MECHANICAL ENGINEERING';
    case BSIE = 'BACHELOR OF SCIENCE IN INDUSTRIAL ENGINEERING';
    case BSEE = 'BACHELOR OF SCIENCE IN ELECTRICAL ENGINEERING';
    case BSCE = 'BACHELOR OF SCIENCE IN CIVIL ENGINEERING';
    case BSA = 'BACHELOR OF SCIENCE IN ACCOUNTANCY';
    case BSMGTA = 'BACHELOR OF SCIENCE IN MANAGEMENT ACCOUNTING';
    case BSMATH = 'BACHELOR OF SCIENCE IN MATHEMATICS';
    case BSENT = 'BACHELOR OF SCIENCE IN ENTREPRENEURSHIP';
    case BSPSYC = 'BACHELOR OF SCIENCE IN PSYCHOLOGY';
    case BSBIO = 'BACHELOR OF SCIENCE IN BIOLOGY';
    case BIOMED = 'BACHELOR OF SCIENCE IN BIOLOGY MAJOR IN MEDICAL BIOLOGY';
    case BIOMIC = 'BACHELOR OF SCIENCE IN BIOLOGY MAJOR IN MICROBIOLOGY';
    case BSN = 'BACHELOR OF SCIENCE IN NURSING';
    case BSBA_OM = 'BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION - OPERATIONS MANAGEMENT';
    case BSBA_FM = 'BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION - FINANCIAL MANAGEMENT';
    case BSBA_HRM = 'BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION - HUMAN RESOURCE MANAGEMENT';
    case BSBA_MM = 'BACHELOR OF SCIENCE IN BUSINESS ADMINISTRATION - MARKETING MANAGEMENT';
    case BSHM = 'BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT';
    case BSHMFB = 'BACHELOR OF SCIENCE IN HOSPITALITY MANAGEMENT - FOOD AND BEVERAGE';
    case BSMLS = 'BACHELOR OF SCIENCE IN MEDICAL LABORATORY SCIENCE';
    case BSTM = 'BACHELOR OF SCIENCE IN TOURISM MANAGEMENT';
    case BEED = 'BACHELOR OF ELEMENTARY EDUCATION';
    case BECED = 'BACHELOR OF EARLY CHILDHOOD EDUCATION';
    case BPED = 'BACHELOR OF PHYSICAL EDUCATION';
    case BSEd_ENGLISH = 'BACHELOR OF SECONDARY EDUCATION MAJOR IN ENGLISH';
    case BSEd_FILIPINO = 'BACHELOR OF SECONDARY EDUCATION-FILIPINO';
    case BSEd_MATH = 'BACHELOR OF SECONDARY EDUCATION MAJOR IN MATHEMATICS';
    case BSEd_SCIENCE = 'BACHELOR OF SECONDARY EDUCATION - SCIENCE';
    case BSNE_EST = 'BACHELOR OF SPECIAL NEEDS EDUCATON MAJOR IN ELEMENTARY SCHOOL TEACHING';
    case BSNE_GEN = 'BACHELOR OF SPECIAL NEEDS EDUCATION-GENERALIST';
    case PHILO = 'BACHELOR OF ARTS IN PHILOSOPHY';
    case ABIS = 'BACHELOR OF ARTS IN INTERNATIONAL STUDIES';
    case BACOM = 'BACHELOR OF ARTS IN COMMUNICATION';
    case BAJOUR = 'BACHELOR OF ARTS IN JOURNALISM';
    case MARCOM = 'BACHELOR OF ARTS IN MARKETING COMMUNICATION';
    case BAPOS = 'BACHELOR OF ARTS IN POLITICAL SCIENCE';
    case BAELS = 'BACHELOR OF ARTS IN ENGLISH LANGUAGE STUDIES';
    case BLIS = 'BACHELOR OF LIBRARY AND INFORMATION SCIENCE';

    public function label(): string
    {
        return $this->value;
    }
}
